version: 2

models:
    - name: silver
      description: "A table for silver layer in dbt model"
sources:
    - name: source
      database: WALMART_DB
      schema: BRONZE
      tables:
        - name: WALMART_STORE_RAW
    - name: source
      database: WALMART_DB
      schema: BRONZE
      tables:
        - name: WALMART_DEPARTMENT_RAW 
    - name: silver
      database: WALMART_DB
      schema: SILVER
      tables:
        - name: WALMART_STORE
    - name: silver
      database: WALMART_DB
      schema: SILVER
      tables:
        - name: WALMART_DEPARTMENT